title: Kavya G
description: > # this means to ignore newlines until "baseurl:"
  4th year undergraduate in Computer Science at IIT Madras.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.gkavya.in" # the base hostname & protocol for your site, e.g. http://example.com
permalink: ':title/'
blog_theme: dark # Or use dark

# Profile information
name: Kavya G
tagline: 4th year undergraduate in Computer Science at IIT Madras.

about-description: Interested in systems topics like networks, blockchain, operating systems, distributed systems, cloud computing etc. 

about-description1: Avid vim user now shifting to Emacs (thanks to org-mode, evil and emacs-lsp). 

# Contact links
email: soldatargent@gmail.com # Add your Email address
github: SilverSoldier # Add your Github handle

# Tracker
analytics:

# Comments
discus-identifier: # Add your Disqus identifier

# Important settings
assets:
  sources:
    - assets/fonts
    - assets/img
    - assets/js
    - assets/stylesheets

# Build settings
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md

gems:
  - jekyll-feed
  - jekyll-assets
exclude:
  - Gemfile
  - Gemfile.lock

include: [_pages]
