title: Kavya G
description: > # this means to ignore newlines until "baseurl:"
  3rd year undergraduate in Computer Science in IIT Madras.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://silversoldier.github.io" # the base hostname & protocol for your site, e.g. http://example.com
permalink: ':title/'
blog_theme: dark # Or use dark

# Profile information
name: Kavya G
tagline: 3rd year undergraduate in Computer Science in IIT Madras.
about-description: Interested in systems and system concepts like networks, blockchain, operating systems. 

# Contact links
email: soldatargent@gmail.com # Add your Email address
github: SilverSoldier # Add your Github handle

# Tracker
analytics:

# Comments
discus-identifier: # Add your Disqus identifier

# Important settings
assets:
  sources:
    - assets/fonts
    - assets/img
    - assets/js
    - assets/stylesheets

# Build settings
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md

gems:
  - jekyll-feed
  - jekyll-assets
exclude:
  - Gemfile
  - Gemfile.lock

include: [_pages]
