title: Kavya G
description: > # this means to ignore newlines until "baseurl:"
  5th year undergraduate (Dual Degree) in Computer Science at IIT Madras.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.gkavya.in" # the base hostname & protocol for your site, e.g. http://example.com
permalink: ':title/'
blog_theme: dark # Or use dark

# Profile information
name: Kavya G
tagline: 5th year undergraduate in Computer Science at IIT Madras.

about-description: Interested in systems (blockchain, operating systems, distributed systems, cloud computing), applied cryptography and systems security. 

about-description1: I don't use Vim or Emacs, I use Vim and Emacs (evil)

#Contact links
email: soldatargent@gmail.com # Add your Email address
github: SilverSoldier # Add your Github handle

# Tracker
analytics:

# Comments
discus-identifier: # Add your Disqus identifier

# Important settings
assets:
  sources:
    - assets/fonts
    - assets/img
    - assets/js
    - assets/stylesheets

# Build settings
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md

gems:
  - jekyll-feed
  - jekyll-assets
exclude:
  - Gemfile
  - Gemfile.lock

include: [_pages]
